name = "HarveySutherland"
uuid = "75d36f5e-971d-4f60-9cc8-d55b8a1a24f8"
authors = ["JJ Garzella <jjgarzella@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "AllocCheck", "Test"]
